version: 2
builds:
  - id: "timesum"
    binary: "timesum"
    main: "./main.go"
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
